### ISSUE TITLE
Documentation Update Process

### ISSUE THREAD

**Issue by AbcSxyZ** [decidim/documentation#10]
I've been around decidim for 2 weeks, trying to install and use decidim, and I was confronted to the documentation. I investigated and ended up with PR [#6364](https://github.com/decidim/decidim/pull/6364). I'm seeing your work but I do not find any public information about the process, I think you're speaking orally together.

I would like to know what are you currently doing around documentation ? Are you just migrating the current one, or are you reorganizing totally the structure ? What is your strategy around the documentation evolution ?

Would be great to learn more about what is happening.

**PS:** Probably not the best place to do that

**Comment by andreslucena** [comment]
Hi @AbcSxyZ 
I agree 100% with you 
One part of the issue is actually that Decidim is built on Ruby on Rails and is not so easy to install it, especially compared to other technologies such as PHP where you can just drop it on a web server and it works.

Also, one other issue is that we have three different kinds of technical users. 
1) Implementers: people that install Decidim for their own organization/city
2) Developers: people that make developments for Decidim core or their own modules 
3) Administrators: people that have access to the /admin panel 

## Installation

This is for *1) Implementers*
With the installation, my idea is to fix the Docker / docker-compose configurations: https://github.com/decidim/decidim/issues/5405 
And to support that as the "only official supported way", like [Discourse](https://github.com/discourse/discourse/blob/master/docs/INSTALL.md) does:

> Hosting Rails applications is complicated. Even if you already have Postgres, Redis and Ruby installed on your server, you still need to worry about running and monitoring your Sidekiq and Rails processes, as well as configuring Nginx. With Docker, our fully optimized Discourse configuration is available to you in a simple container, along with a web-based GUI that makes upgrading to new versions of Discourse as easy as clicking a button.

This has some limitations that I still don't know how to easily fix, most notably:
1) Decidim is not an application as Discourse, it's a framework where you can hack more things.
2) There's the need for best practices (multiple environments/deployment/CI) that will make it harder to work with docker-compose (or at least I don't have a solution yet). For instance, one thing that I don't like about the Platoniq guide is that it generates the application on the server itself, and on Rails, you should generate it locally (development environment), push it to a git repository and then make the deploy (through Capistrano) - ideally, you'd also configure a CI integrated with the git repository. This is explained in [Aleveteli documentation](https://alaveteli.org/docs/installing/). 

## Documentation

We have lots of documentation sites/repositories, more than 20. That's because the technology that we're using (Antora) allows you to have multi-repository and we tried to do that but is too complex to work on all those documents and documentation stagnated. That's because too many people that work with Decidim on Barcelona are not proficient with Antora / technology in general, and instead of working with Antora, they kept working with Google Drive :(  - this is especially painful with the Admin documentation, where we have it published until v0.10 and we're releasing v0.22 :disappointed: 
We also have some documentation that is in Spanish only. That's because too many people that work with Decidim in Barcelona are not proficient in English.
There were some tests made by me for having a developer document (mostly by copying the decidim/decidim repository and some markdown README for the modules) but they also stagnated
Finally, we had lots of documents but nothing on documenting the documentation infrastructure or how every repository works  

My idea for fixing this is: 
1) Make a mono repository/mono document project: that's this repository - #1 
2) Move all the legacy documents: #5 - that'd be other repository called documentation-legacy, it'll work as a backup / for transparency. I prefer to do that instead of deprecating or archiving the repositories as there's too much and it brings too much noise 
3) Regarding the "Developing": I think the best solution would be to convert the markdown docs/ to Asciidoc and make it compatible with Antora. That way we could also include that on this same document. I don't like having it on two different repositories but I don't like also to have the Developers documentation separated as if it's not comfortable to work with people will not update it. I'm looking for the issue number but I didn't report it yet. 

---- 

Hope that this clarifies/gives transparency for you, I can use this issue as the place to keep you and the community updated with the improvements/doubts of all this process.

**Comment by andreslucena** [comment]
FYI, we've just published the new version of the docs site (the one on this repository) on docs.decidim.org 

@AbcSxyZ if you want to contribute to the documentation, a really good starter would be the admin's manual at #13

**Comment by andreslucena** [comment]
I'm reviewing old issues. I'm closing this one as all the initial questions were answered. @AbcSxyZ feel free to open a new issue if you have any other question!

**Comment by AbcSxyZ** [comment]
It was a quick visit for me around Decidim, I didn't have the opportunity to work on a project related to Decidim & democratic participation. Everything is all right, hope your documentation rocks now :)
Wish the best, thanks for your job !
